dependencies = []
description = "Small DNS server resolving database hostnames inside the infrastructure"
destination_server = ["internal"]
flags = ["deployed-by-chef"]
languages = ["go"]
owner = "leo@scalingo.com"
team = "IST"
version = "1.1.0"
